name: Шаблон сборки

on:
  pull_request:
    types: [opened, synchronize]   # при открытии PR и новых коммитах в PR
    branches: [main]               # только main

env:
  IMAGE_NAME: ${{ secrets.IMAGE_ENV_NAME }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_ENV_NAME }}
  HOST_PORT: ${{ secrets.ENV_SERVICE_HOST_PORT }}
  CONTAINER_PORT: ${{ secrets.ENV_SERVICE_CONTAINER_PORT }}

name: Сборка и деплой

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Сборка Docker-образа
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .
      
      - name: Сохранить образ
        run: docker save ${{ env.IMAGE_NAME }}:latest | gzip > image.tar.gz
      
      - name: Копировать образ на хост
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: image.tar.gz
          target: /tmp/
      
      - name: Деплой на хосте
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker load < /tmp/image.tar.gz
            
            docker stop ${{ env.CONTAINER_NAME }} 2>/dev/null || true
            docker rm ${{ env.CONTAINER_NAME }} 2>/dev/null || true
            
            docker run -d \
              --name ${{ env.CONTAINER_NAME }} \
              --restart unless-stopped \
              -p ${{ env.HOST_PORT }}:${{ env.CONTAINER_PORT }} \
              -e PROJECT_NAME="${{ secrets.PROJECT_NAME }}" \
              -e VERSION="${{ secrets.VERSION }}" \
              -e ENVIRONMENT="${{ secrets.ENVIRONMENT }}" \
              -e POSTGRESQL_HOST="${{ secrets.POSTGRESQL_HOST }}" \
              -e POSTGRESQL_PORT="${{ secrets.POSTGRESQL_PORT }}" \
              -e POSTGRESQL_USER="${{ secrets.POSTGRESQL_USER }}" \
              -e POSTGRESQL_PASSWORD="${{ secrets.POSTGRESQL_PASSWORD }}" \
              -e POSTGRESQL_DBNAME="${{ secrets.POSTGRESQL_DBNAME }}" \
              ${{ env.IMAGE_NAME }}:latest
            
            rm /tmp/image.tar.gz
            docker ps --filter name=${{ env.CONTAINER_NAME }}
